openapi: 3.0.0
info:
  title: MOCK API
  description: Returns mock data
  contact:
    email: tdavis53@my.bcit.ca
  version: 1.0.0
servers:
  - url: /
paths:
  /mock_get:
    get:
      summary: mock Summary
      operationId: app.mock_get
      description: mock description
      parameters:
        - name: index
          in: query
          description: Specifies the index
          schema:
            type: integer
            example: 1
      responses:
        '201':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
    
  /mock_post:
    post:
      summary: mock summary
      description: mock desc
      operationId: app.mock_post
      requestBody:
        description: mock body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EventLog'
      responses:
        "201":
          description: job listing created
        "400":
          description: "invalid input, object invalid"

components:
  schemas:
    EventLog:
      type: object
      properties:
        "0001":
          type: integer
          example: 1
        "0002":
          type: integer
          example: 2
        "0003":
          type: integer
          example: 1
        "0004":
          type: integer
          example: 1
      example:
        "0001": 1
        "0002": 2
        "0003": 1
        "0004": 1

    MockEvent:
      type: object
      properties:
        "response":
          type: integer
          example: 1
         